# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'pictures')),
            ],
            options={
                'db_table': 'ImageUpload',
            },
        ),
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('usernum', models.IntegerField()),
            ],
            options={
                'db_table': 'UserCount',
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('imageid', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
            options={
                'db_table': 'UserRating',
            },
        ),
        migrations.CreateModel(
            name='UserRatingForScud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('imageid', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
            options={
                'db_table': 'UserRatingForScud',
            },
        ),
    ]
